In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
np.asarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4, 5]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [14]:
a = np.array(l)
a

array([1, 2, 3, 4, 5])

In [15]:
c = a # solocopy same location store and samechange kerega

In [16]:
c

array([1, 2, 3, 4, 5])

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
c[0] = 100

In [19]:
c

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
d = np.copy(a) # deepcopy  no change store new location dono 

In [22]:
d

array([100,   2,   3,   4,   5])

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
a[1] = 101

In [25]:
a

array([100, 101,   3,   4,   5])

In [26]:
d

array([100,   2,   3,   4,   5])

In [27]:
np.fromfunction(lambda i,j : i==j, [3,3])

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i*j, [3,3])

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*1 for i in range(5))

In [30]:
iterable

<generator object <genexpr> at 0x0000024305F38E10>

In [31]:
np.fromiter(iterable,float)

array([0., 1., 2., 3., 4.])

In [32]:
np.fromstring("234 567", sep = " ")

array([234., 567.])

In [36]:
np.fromstring("2,6",sep = ",")

array([2., 6.])

#Numpy - Data Types.

In [55]:
#Numpy - Data Types.

l = [2,3,4,5]

In [56]:
ar = np.array(l)

In [57]:
ar

array([2, 3, 4, 5])

In [58]:
ar.ndim

1

In [59]:
ar.size

4

In [60]:
ar.shape

(4,)

In [61]:
ar2 = np.array([[2,3,4,5],[6,7,8,9]])

In [62]:
ar2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [63]:
ar2.ndim

2

In [64]:
ar2.size

8

In [65]:
ar2.shape

(2, 4)

In [71]:
ar2.dtype()

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [72]:
ar2.dtype

dtype('int64')

In [66]:
ar

array([2, 3, 4, 5])

In [68]:
ar2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [73]:
np.array([(1.4,45,45), (23,45,66)])

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [74]:
ar22 = np.array([(1.4,45,45), (23,45,66)])

In [75]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [76]:
ar22.dtype

dtype('float64')

In [77]:
ar22.shape

(2, 3)

In [78]:
ar22.ndim

2

In [79]:
range(5)

range(0, 5)

In [80]:
list(range(5))

[0, 1, 2, 3, 4]

In [81]:
list(range(2.3,5))

TypeError: 'float' object cannot be interpreted as an integer

In [82]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [84]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [85]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [88]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [89]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [91]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [93]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [94]:
ar4 = np.zeros((3,4,2,3))

In [95]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [96]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
on = np.ones((2,3,2))

In [99]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [102]:
on + 3


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [103]:
on * 3

array([[[3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.]]])

In [104]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [114]:
np.eye(5) # diagonal ya fir indetical metrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [116]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [126]:
arr = np.random.randn(3,4)

In [127]:
arr

array([[ 0.11749282,  0.94154806, -0.35186051,  1.52219789],
       [-0.05186119, -0.87628264, -2.11533135,  0.65544224],
       [ 0.45255108,  0.07773751,  0.47215038, -0.32244655]])

In [128]:
np.random.rand(3,4)

array([[0.40722591, 0.96566498, 0.02872507, 0.882591  ],
       [0.28248457, 0.74462364, 0.24065767, 0.85285392],
       [0.72851693, 0.02877942, 0.73667808, 0.41601804]])

In [129]:
import pandas as pd

In [130]:
pd.DataFrame(arr)

0         1         2         3
0  0.117493  0.941548 -0.351861  1.522198
1 -0.051861 -0.876283 -2.115331  0.655442
2  0.452551  0.077738  0.472150 -0.322447

In [131]:
np.random.randint(1,100, (4,4))

array([[ 7, 65, 20, 86],
       [70, 48, 32, 48],
       [99, 88, 56, 76],
       [64, 60, 89, 73]], dtype=int32)

In [132]:
arr1 = np.random.randint(1,100, (4,4))

In [133]:
pd.DataFrame(arr1)

0   1   2   3
0  84  42  73  60
1  90  97  83  57
2  19  51  50  24
3  16  14  22  90

In [139]:
arr1 = pd.DataFrame(np.random.randint(1,100, (4,4))).to_csv('test_csv')

In [141]:
arr = np.random.rand(3,4)

In [142]:
arr

array([[0.31769947, 0.30466777, 0.4063747 , 0.22900006],
       [0.92129695, 0.35653977, 0.5919434 , 0.13216369],
       [0.28218521, 0.69086035, 0.83599285, 0.4671147 ]])

In [143]:
arr.reshape(6,2)

array([[0.31769947, 0.30466777],
       [0.4063747 , 0.22900006],
       [0.92129695, 0.35653977],
       [0.5919434 , 0.13216369],
       [0.28218521, 0.69086035],
       [0.83599285, 0.4671147 ]])

In [149]:
arr.reshape(6,-1)

array([[0.31769947, 0.30466777],
       [0.4063747 , 0.22900006],
       [0.92129695, 0.35653977],
       [0.5919434 , 0.13216369],
       [0.28218521, 0.69086035],
       [0.83599285, 0.4671147 ]])

In [151]:
arr1 = arr.reshape(6,-13455651235)

In [153]:
arr1

array([[0.31769947, 0.30466777],
       [0.4063747 , 0.22900006],
       [0.92129695, 0.35653977],
       [0.5919434 , 0.13216369],
       [0.28218521, 0.69086035],
       [0.83599285, 0.4671147 ]])

In [158]:
arr1[1][1]

np.float64(0.2290000591844683)

In [160]:
arr1[2:5,1]

array([0.35653977, 0.13216369, 0.69086035])

In [162]:
arr = np.random.randint(1,100, (5,5))

In [163]:
arr

array([[79, 26, 17, 97, 12],
       [54, 53, 49, 66, 45],
       [44, 33, 61, 78, 75],
       [92, 20, 36, 31, 58],
       [80, 55, 17, 78, 79]], dtype=int32)

In [171]:
arr[3][1]

np.int32(20)

In [174]:
arr[4,2]

np.int32(17)

In [175]:
arr

array([[79, 26, 17, 97, 12],
       [54, 53, 49, 66, 45],
       [44, 33, 61, 78, 75],
       [92, 20, 36, 31, 58],
       [80, 55, 17, 78, 79]], dtype=int32)

In [177]:
arr>75

array([[ True, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True, False, False,  True,  True]])

In [178]:
arr[arr>75]

array([79, 97, 78, 92, 80, 78, 79], dtype=int32)

In [179]:
arr

array([[79, 26, 17, 97, 12],
       [54, 53, 49, 66, 45],
       [44, 33, 61, 78, 75],
       [92, 20, 36, 31, 58],
       [80, 55, 17, 78, 79]], dtype=int32)

In [182]:
arr[3:5, [3,4]]

array([[31, 58],
       [78, 79]], dtype=int32)

In [184]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [185]:
arr1

array([[1, 2, 1],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [186]:
arr2

array([[2, 1, 1],
       [2, 2, 1],
       [2, 2, 1]], dtype=int32)

In [187]:
arr1 + arr2

array([[3, 3, 2],
       [4, 4, 2],
       [4, 4, 2]], dtype=int32)

In [189]:
arr1 * arr2   # yaha pe isne index wise * kiya hai 

array([[2, 2, 1],
       [4, 4, 1],
       [4, 4, 1]], dtype=int32)

In [191]:
# but muje matric form mai * krna hai 

In [192]:
arr1@arr2

array([[ 8,  7,  4],
       [10,  8,  5],
       [10,  8,  5]], dtype=int32)

In [193]:
arr/0

C:\Users\viren\AppData\Local\Temp\ipykernel_17800\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [194]:
arr1 + 100

array([[101, 102, 101],
       [102, 102, 101],
       [102, 102, 101]], dtype=int32)

In [197]:
arr2 = arr2**2

In [198]:
arr2

array([[4, 1, 1],
       [4, 4, 1],
       [4, 4, 1]], dtype=int32)

#Numpy – Broadcasting.

In [202]:
arr = np.zeros((4,4))

In [203]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [204]:
row = np.array([1,2,3,4])

In [205]:
row

array([1, 2, 3, 4])

In [207]:
arr + row  # rowwise add kerega

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [208]:
row.T

array([1, 2, 3, 4])

In [209]:
col = np.array([[1,2,3,4]])

In [210]:
col

array([[1, 2, 3, 4]])

In [211]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [212]:
col

array([[1, 2, 3, 4]])

In [213]:
arr1 = np.random.randint(1,4, (3,4))

In [217]:
arr1

array([[2, 3, 3, 3],
       [1, 3, 1, 2],
       [1, 3, 3, 3]], dtype=int32)

In [218]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 1.73205081, 1.73205081],
       [1.        , 1.73205081, 1.        , 1.41421356],
       [1.        , 1.73205081, 1.73205081, 1.73205081]])

In [219]:
np.exp(arr1)

array([[ 7.3890561 , 20.08553692, 20.08553692, 20.08553692],
       [ 2.71828183, 20.08553692,  2.71828183,  7.3890561 ],
       [ 2.71828183, 20.08553692, 20.08553692, 20.08553692]])