In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
np.asarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4, 5]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [14]:
a = np.array(l)
a

array([1, 2, 3, 4, 5])

In [15]:
c = a # solocopy same location store and samechange kerega

In [16]:
c

array([1, 2, 3, 4, 5])

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
c[0] = 100

In [19]:
c

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
d = np.copy(a) # deepcopy  no change store new location dono 

In [22]:
d

array([100,   2,   3,   4,   5])

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
a[1] = 101

In [25]:
a

array([100, 101,   3,   4,   5])

In [26]:
d

array([100,   2,   3,   4,   5])

In [27]:
np.fromfunction(lambda i,j : i==j, [3,3])

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i*j, [3,3])

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*1 for i in range(5))

In [30]:
iterable

<generator object <genexpr> at 0x0000024305F38E10>

In [31]:
np.fromiter(iterable,float)

array([0., 1., 2., 3., 4.])

In [32]:
np.fromstring("234 567", sep = " ")

array([234., 567.])

In [36]:
np.fromstring("2,6",sep = ",")

array([2., 6.])

#Numpy - Data Types.

In [55]:
#Numpy - Data Types.

l = [2,3,4,5]

In [56]:
ar = np.array(l)

In [57]:
ar

array([2, 3, 4, 5])

In [58]:
ar.ndim

1

In [59]:
ar.size

4

In [60]:
ar.shape

(4,)

In [61]:
ar2 = np.array([[2,3,4,5],[6,7,8,9]])

In [62]:
ar2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [63]:
ar2.ndim

2

In [64]:
ar2.size

8

In [65]:
ar2.shape

(2, 4)

In [71]:
ar2.dtype()

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [72]:
ar2.dtype

dtype('int64')

In [66]:
ar

array([2, 3, 4, 5])

In [68]:
ar2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [73]:
np.array([(1.4,45,45), (23,45,66)])

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [74]:
ar22 = np.array([(1.4,45,45), (23,45,66)])

In [75]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [76]:
ar22.dtype

dtype('float64')

In [77]:
ar22.shape

(2, 3)

In [78]:
ar22.ndim

2

In [79]:
range(5)

range(0, 5)

In [80]:
list(range(5))

[0, 1, 2, 3, 4]

In [81]:
list(range(2.3,5))

TypeError: 'float' object cannot be interpreted as an integer

In [82]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [84]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [85]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [88]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [89]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [91]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [93]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [94]:
ar4 = np.zeros((3,4,2,3))

In [95]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [96]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [98]:
on = np.ones((2,3,2))

In [99]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [102]:
on + 3


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [103]:
on * 3

array([[[3., 3.],
        [3., 3.],
        [3., 3.]],

       [[3., 3.],
        [3., 3.],
        [3., 3.]]])

In [104]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
np.eye(5) # diagonal ya fir indetical metrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])