In [1]:
import numpy as np


#Numpy - Array Manipulation.

In [2]:
arr = np.random.randint(1,10 , (3,4))

In [3]:
arr

array([[4, 9, 6, 8],
       [7, 9, 3, 7],
       [5, 3, 8, 5]], dtype=int32)

In [4]:
arr.reshape(6,2)

array([[4, 9],
       [6, 8],
       [7, 9],
       [3, 7],
       [5, 3],
       [8, 5]], dtype=int32)

In [5]:
arr.reshape(2,6)

array([[4, 9, 6, 8, 7, 9],
       [3, 7, 5, 3, 8, 5]], dtype=int32)

In [7]:
arr.reshape(2,-2)

array([[4, 9, 6, 8, 7, 9],
       [3, 7, 5, 3, 8, 5]], dtype=int32)

In [8]:
arr.reshape(2,-2445435564)

array([[4, 9, 6, 8, 7, 9],
       [3, 7, 5, 3, 8, 5]], dtype=int32)

In [9]:
arr.T

array([[4, 7, 5],
       [9, 9, 3],
       [6, 3, 8],
       [8, 7, 5]], dtype=int32)

In [10]:
arr

array([[4, 9, 6, 8],
       [7, 9, 3, 7],
       [5, 3, 8, 5]], dtype=int32)

In [12]:
arr.flatten()

array([4, 9, 6, 8, 7, 9, 3, 7, 5, 3, 8, 5], dtype=int32)

In [13]:
arr1 = np.array([1,2,3,3,4])

In [14]:
arr1

array([1, 2, 3, 3, 4])

In [15]:
arr1.ndim

1

In [17]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 3, 3, 4]])

In [18]:
np.expand_dims(arr1,axis = 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [19]:
arr

array([[4, 9, 6, 8],
       [7, 9, 3, 7],
       [5, 3, 8, 5]], dtype=int32)

In [20]:
np.squeeze(arr)

array([[4, 9, 6, 8],
       [7, 9, 3, 7],
       [5, 3, 8, 5]], dtype=int32)

In [21]:
data = np.array([[1],[2],[3]])

In [22]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.squeeze(data)

array([1, 2, 3])

In [25]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [26]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [27]:
arr1

array([1, 2, 3, 3, 4])

In [32]:
np.roll(arr1,4)

array([2, 3, 3, 4, 1])

In [33]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#Numpy - Binary Operators.

In [34]:
arr1 = np.random.randint(1,10 , (3,4))

In [36]:
arr2 = np.random.randint(1,10 , (3,4))

In [37]:
arr1

array([[3, 7, 4, 2],
       [8, 5, 5, 6],
       [9, 9, 6, 5]], dtype=int32)

In [38]:
arr2

array([[1, 4, 3, 9],
       [7, 6, 5, 5],
       [1, 9, 2, 6]], dtype=int32)

In [39]:
arr1 + arr2

array([[ 4, 11,  7, 11],
       [15, 11, 10, 11],
       [10, 18,  8, 11]], dtype=int32)

In [40]:
arr1*arr2

array([[ 3, 28, 12, 18],
       [56, 30, 25, 30],
       [ 9, 81, 12, 30]], dtype=int32)

In [41]:
arr1/arr2

array([[3.        , 1.75      , 1.33333333, 0.22222222],
       [1.14285714, 0.83333333, 1.        , 1.2       ],
       [9.        , 1.        , 3.        , 0.83333333]])

In [42]:
arr1%arr2

array([[0, 3, 1, 2],
       [1, 5, 0, 1],
       [0, 0, 0, 5]], dtype=int32)

In [43]:
arr1-arr2

array([[ 2,  3,  1, -7],
       [ 1, -1,  0,  1],
       [ 8,  0,  4, -1]], dtype=int32)

In [44]:
arr1 ** arr2

array([[        3,      2401,        64,       512],
       [  2097152,     15625,      3125,      7776],
       [        9, 387420489,        36,     15625]], dtype=int32)

In [45]:
arr1 & arr2

array([[1, 4, 0, 0],
       [0, 4, 5, 4],
       [1, 9, 2, 4]], dtype=int32)

#Numpy - String Functions.

In [47]:
arr = np.array(['virendra', "praveen"])

In [48]:
arr

array(['virendra', 'praveen'], dtype='<U8')

In [49]:
np.char.upper(arr)

array(['VIRENDRA', 'PRAVEEN'], dtype='<U8')

In [50]:
np.char.title(arr)

array(['Virendra', 'Praveen'], dtype='<U8')

In [51]:
np.char.capitalize(arr)

array(['Virendra', 'Praveen'], dtype='<U8')

#Numpy - Mathematical Functions.

In [52]:
arr1

array([[3, 7, 4, 2],
       [8, 5, 5, 6],
       [9, 9, 6, 5]], dtype=int32)

In [54]:
np.sin(arr1)

array([[ 0.14112001,  0.6569866 , -0.7568025 ,  0.90929743],
       [ 0.98935825, -0.95892427, -0.95892427, -0.2794155 ],
       [ 0.41211849,  0.41211849, -0.2794155 , -0.95892427]])

In [55]:
np.cos(arr1)

array([[-0.9899925 ,  0.75390225, -0.65364362, -0.41614684],
       [-0.14550003,  0.28366219,  0.28366219,  0.96017029],
       [-0.91113026, -0.91113026,  0.96017029,  0.28366219]])

In [56]:
np.tan(arr1)

array([[-0.14254654,  0.87144798,  1.15782128, -2.18503986],
       [-6.79971146, -3.38051501, -3.38051501, -0.29100619],
       [-0.45231566, -0.45231566, -0.29100619, -3.38051501]])

In [57]:
np.power(arr1,2)

array([[ 9, 49, 16,  4],
       [64, 25, 25, 36],
       [81, 81, 36, 25]], dtype=int32)

In [58]:
np.mean(arr1)

np.float64(5.75)

In [60]:
np.std(arr1)

np.float64(2.1262251370288454)

In [61]:
np.var(arr1)

np.float64(4.520833333333333)

In [62]:
np.max(arr1)

np.int32(9)