In [1]:
import numpy as np

#Sort, Search & Counting Functions.

In [2]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [3]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [4]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [5]:
np.searchsorted(arr, 34)

np.int64(12)

In [6]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [7]:
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [9]:
np.count_nonzero(arr1)

np.int64(2)

In [10]:
np.where(arr > 6)

(array([5, 8]),)

In [11]:
np.extract(arr>4, arr)

array([  5,   6,  72, 455,   5,   6,   6])

#Numpy - Byte Swapping.

In [12]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [13]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

#Numpy - Copies &Views.

In [14]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [16]:
a = np.copy(arr)

In [17]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
b = arr.view()

In [21]:
b


array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
b[0] = 100

In [23]:
b

array([100,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [24]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

#Numpy - Matrix Library.